CREATE DATABASE IF NOT EXISTS TMDT;
USE TMDT;

-- 1. Region
CREATE TABLE IF NOT EXISTS Region (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RegionName VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Users
CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    BirthDate DATE NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    PhoneNumber VARCHAR(15) UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Avt VARCHAR(255),
    Address VARCHAR(255) NOT NULL,
    RegionID INT NULL,
    Statuses TINYINT(1) NOT NULL DEFAULT 0,
    CreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastLogin TIMESTAMP NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_region FOREIGN KEY (RegionID)
        REFERENCES Region(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Accounts
CREATE TABLE IF NOT EXISTS Accounts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    UserName VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Statuses TINYINT(1) NOT NULL DEFAULT 1,
    CreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_user FOREIGN KEY (UserID)
        REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Admins
CREATE TABLE IF NOT EXISTS Admins (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AdminName VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Roles VARCHAR(50),
    CreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. TypeProduct
CREATE TABLE IF NOT EXISTS TypeProduct (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TypeName VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Product
CREATE TABLE IF NOT EXISTS Product (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Descriptions TEXT,
    TypeID INT NOT NULL,
    CONSTRAINT fk_product_type FOREIGN KEY (TypeID)
        REFERENCES TypeProduct(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. SizeProduct
CREATE TABLE IF NOT EXISTS SizeProduct (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SizeName VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Image
CREATE TABLE IF NOT EXISTS Image (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ImgPath VARCHAR(255) NOT NULL,
    CreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. ColorProduct
CREATE TABLE IF NOT EXISTS ColorProduct (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT NOT NULL,
    ColorName VARCHAR(100) DEFAULT 'Default',
    CreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ColorProduct_Product_Color (ProductID, ColorName),
    CONSTRAINT fk_colorproduct_product FOREIGN KEY (ProductID)
        REFERENCES Product(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. ProductImg
CREATE TABLE IF NOT EXISTS ProductImg (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT NOT NULL,
    ImgID INT NOT NULL,
    UNIQUE KEY uq_ProductImg (ProductID, ImgID),
    CONSTRAINT fk_productimg_product FOREIGN KEY (ProductID)
        REFERENCES Product(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_productimg_image FOREIGN KEY (ImgID)
        REFERENCES Image(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. ColorProductImage
CREATE TABLE IF NOT EXISTS ColorProductImage (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ColorProductID INT NOT NULL,
    ImgID INT NOT NULL,
    AddedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ColorProduct_Img (ColorProductID, ImgID),
    CONSTRAINT fk_cpi_colorproduct FOREIGN KEY (ColorProductID)
        REFERENCES ColorProduct(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cpi_image FOREIGN KEY (ImgID)
        REFERENCES Image(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. Quantity
CREATE TABLE IF NOT EXISTS Quantity (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QuantityValue INT NOT NULL,
    SizeID INT NOT NULL,
    ColorID INT NOT NULL,
    ProductID INT NOT NULL,
    UNIQUE KEY uq_ProductSizeColor (ProductID, SizeID, ColorID),
    CONSTRAINT fk_quantity_size FOREIGN KEY (SizeID)
        REFERENCES SizeProduct(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_quantity_color FOREIGN KEY (ColorID)
        REFERENCES ColorProduct(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_quantity_product FOREIGN KEY (ProductID)
        REFERENCES Product(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. Price
CREATE TABLE IF NOT EXISTS Price (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT NOT NULL,
    Price DECIMAL(15,2) NOT NULL,
    UpdatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ProductPrice (ProductID),
    CONSTRAINT fk_price_product FOREIGN KEY (ProductID)
        REFERENCES Product(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 14. Cart
CREATE TABLE IF NOT EXISTS Cart (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    CreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Statuses TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT fk_cart_user FOREIGN KEY (UserID)
        REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 15. CartItem
CREATE TABLE IF NOT EXISTS CartItem (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CartID INT NOT NULL,
    SizeID INT NOT NULL,
    ColorID INT NOT NULL,
    ProductID INT NOT NULL,
    Volume INT NOT NULL,
    UnitPrice DECIMAL(15,2) NOT NULL,
    TotalPrice DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_cartitem_cart FOREIGN KEY (CartID)
        REFERENCES Cart(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cartitem_size FOREIGN KEY (SizeID)
        REFERENCES SizeProduct(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cartitem_color FOREIGN KEY (ColorID)
        REFERENCES ColorProduct(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cartitem_product FOREIGN KEY (ProductID)
        REFERENCES Product(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 16. StatusInvoice
CREATE TABLE IF NOT EXISTS StatusInvoice (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    StatusName VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 17. Invoice
CREATE TABLE IF NOT EXISTS Invoice (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    DateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QuantityTypes INT DEFAULT 1,
    StatusID INT NOT NULL,
    Payment VARCHAR(50) DEFAULT 'Unpaid',
    States VARCHAR(50) DEFAULT 'Done',
    TotalCost DECIMAL(15,2) DEFAULT 0.00,
    CartID INT NULL,
    CONSTRAINT fk_invoice_user FOREIGN KEY (UserID)
        REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_invoice_status FOREIGN KEY (StatusID)
        REFERENCES StatusInvoice(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_invoice_cart FOREIGN KEY (CartID)
        REFERENCES Cart(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 18. Transactions
CREATE TABLE IF NOT EXISTS Transactions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceID INT NOT NULL,
    partnerCode VARCHAR(50),
    orderId VARCHAR(50) NOT NULL,
    requestId VARCHAR(50),
    amount DECIMAL(15,2) NOT NULL,
    transId VARCHAR(50),
    resultCode INT NOT NULL,
    message VARCHAR(255),
    payType VARCHAR(50),
    responseTime BIGINT,
    extraData TEXT,
    Status ENUM('pending', 'success', 'failed') NOT NULL DEFAULT 'pending',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trans_invoice FOREIGN KEY (InvoiceID)
        REFERENCES Invoice(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 19. Chat
CREATE TABLE IF NOT EXISTS Chat (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    AdminID INT NULL,
    ProductID INT NULL,
    Message TEXT NOT NULL,
    SendTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_user FOREIGN KEY (UserID)
        REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_chat_admin FOREIGN KEY (AdminID)
        REFERENCES Admins(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_chat_product FOREIGN KEY (ProductID)
        REFERENCES Product(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 20. Conversations
CREATE TABLE IF NOT EXISTS Conversations (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    AdminID INT NULL,
    Subject VARCHAR(255),
    Status ENUM('open','pending','closed') NOT NULL DEFAULT 'open',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastMessageAt DATETIME NULL,
    CONSTRAINT fk_conv_user FOREIGN KEY (UserID)
        REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_conv_admin FOREIGN KEY (AdminID)
        REFERENCES Admins(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 21. PageView
CREATE TABLE IF NOT EXISTS PageView (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VisitorID VARCHAR(255) NOT NULL,
    PageURL VARCHAR(500),
    ViewTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserAgent TEXT,
    IPAddress VARCHAR(45)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 22. UserLogins
CREATE TABLE IF NOT EXISTS UserLogins (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    LoginTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_userlogins_user FOREIGN KEY (UserID)
        REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
